const mongoose=require('mongoose');
const applicationSchema=new mongoose.Schema({

    name:{
        type:String,
        require:true
    },
    email:{
        type:String,
        require:true
    },
    phoneno:{
        type:String
    },
    password:{
        type:String,
        require:true
    },
    dob:{
        type:String
    },
    skills:[{
        type:String
    }],
    secondarySkills:[{
        type:String
    }],
    experience:{
        type:String
    },
    state:{
        type:String  
    },
    city:{
        type:String
    },
    readytolocate:{
        type:Boolean
    },
    comment:{
        type:String,
        default:""
    },
    createdat:{
        type:Date,
        default:Date.now()
    },
    isAdmin:{
        type:Boolean,
        default:false
    },
    degree:{
        type:String
    },
    resume:{
        type:String
    },
    coverletter:{
        type:String
    },
    bestTimeToReach:{
        type:String
    },
    additionalExperience:{
        type:String
    },
    
})

module.exports=mongoose.model('Applications',applicationSchema)